# Generated by Django 4.1 on 2022-09-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_rename_tables_table_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='quantity',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
