# Generated by Django 4.1 on 2022-09-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_restaurant_rename_quantity_table_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='food',
        ),
    ]
